name: Docker image
on:
  push:
    branches:
      - master
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variables
        id: variables
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build python3.8-nodejs14-aws2.2.30
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg SRC_TAG=python3.8-nodejs14 \
            -t a00s/${{ steps.variables.outputs.REPOSITORY_NAME }}:python3.8-nodejs14-aws2.2.30 \
            . \
            --push

      - name: Build python3.9-nodejs14-aws2.2.30
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg SRC_TAG=python3.9-nodejs14 \
            -t a00s/${{ steps.variables.outputs.REPOSITORY_NAME }}:python3.9-nodejs14-aws2.2.30 \
            . \
            --push

      - name: Build python3.8-nodejs16-aws2.2.30
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg SRC_TAG=python3.8-nodejs16 \
            -t a00s/${{ steps.variables.outputs.REPOSITORY_NAME }}:python3.8-nodejs16-aws2.2.30 \
            . \
            --push

      - name: Build python3.9-nodejs16-aws2.2.30
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg SRC_TAG=python3.9-nodejs16 \
            -t a00s/${{ steps.variables.outputs.REPOSITORY_NAME }}:python3.9-nodejs16-aws2.2.30 \
            . \
            --push
